pip install nvitop
pip install pytrec-eval
pip install pyserini==0.20.0
pip install packaging
pip install peft
pip install bitsandbytes
pip install tevatron
pip install anthropic
pip install wandb
pip install openai
pip install ftfy
pip install python-dotenv
pip install tiktoken
pip install dacite
pip install fschat[model_worker]
pip install vllm==0.6.2
pip install tenacity
pip install flash_attn
pip install accelerate==0.34.0
pip install deepspeed==0.14.5
pip install transformers==4.45.2
pip install faiss_gpu
pip install matplotlib