import numpy as np
import json

THE_INDEX = {
    'dl19': 'msmarco-v1-passage',
    'dl20': 'msmarco-v1-passage',
    "dl21": "msmarco-v2-passage",
    "dl22": "msmarco-v2-passage",
    "dl23": "msmarco-v2-passage",
    'msmarco': 'msmarco-v1-passage',
    'covid': 'beir-v1.0.0-trec-covid-flat',
    'arguana': 'beir-v1.0.0-arguana-flat',
    'touche': 'beir-v1.0.0-webis-touche2020-flat',
    'news': 'beir-v1.0.0-trec-news-flat',
    'scifact': 'beir-v1.0.0-scifact-flat',
    'fiqa': 'beir-v1.0.0-fiqa-flat',
    'scidocs': 'beir-v1.0.0-scidocs-flat',
    'nfc': 'beir-v1.0.0-nfcorpus-flat',
    'quora': 'beir-v1.0.0-quora-flat',
    'dbpedia': 'beir-v1.0.0-dbpedia-entity-flat',
    'fever': 'beir-v1.0.0-fever-flat',
    'climate-fever': 'beir-v1.0.0-climate-fever-flat',
    'robust04': 'beir-v1.0.0-robust04-flat',
    'signal': 'beir-v1.0.0-signal1m-flat',
    'hotpotqa': 'beir-v1.0.0-hotpotqa-flat',
    'nq': 'beir-v1.0.0-nq-flat',
    'nfcorpus': 'beir-v1.0.0-nfcorpus-flat',
    'bioasq': 'beir-v1.0.0-bioasq-flat',


    'mrtydi-ar': 'mrtydi-v1.1-arabic',
    'mrtydi-bn': 'mrtydi-v1.1-bengali',
    'mrtydi-fi': 'mrtydi-v1.1-finnish',
    'mrtydi-id': 'mrtydi-v1.1-indonesian',
    'mrtydi-ja': 'mrtydi-v1.1-japanese',
    'mrtydi-ko': 'mrtydi-v1.1-korean',
    'mrtydi-ru': 'mrtydi-v1.1-russian',
    'mrtydi-sw': 'mrtydi-v1.1-swahili',
    'mrtydi-te': 'mrtydi-v1.1-telugu',
    'mrtydi-th': 'mrtydi-v1.1-thai',
}

THE_TOPICS = {
    'dl19': 'dl19-passage',
    'dl20': 'dl20',
    "dl21": "dl21",
    "dl22": "dl22",
    'msmarco': 'msmarco-passage-dev-subset',
    'covid': 'beir-v1.0.0-trec-covid-test',
    'arguana': 'beir-v1.0.0-arguana-test',
    'touche': 'beir-v1.0.0-webis-touche2020-test',
    'news': 'beir-v1.0.0-trec-news-test',
    'scifact': 'beir-v1.0.0-scifact-test',
    'fiqa': 'beir-v1.0.0-fiqa-test',
    'scidocs': 'beir-v1.0.0-scidocs-test',
    'nfc': 'beir-v1.0.0-nfcorpus-test',
    'quora': 'beir-v1.0.0-quora-test',
    'dbpedia': 'beir-v1.0.0-dbpedia-entity-test',
    'fever': 'beir-v1.0.0-fever-test',
    'robust04': 'beir-v1.0.0-robust04-test',
    'signal': 'beir-v1.0.0-signal1m-test',
    'fever': 'beir-v1.0.0-fever-test',
    'climate-fever': 'beir-v1.0.0-climate-fever-test',
    'hotpotqa': 'beir-v1.0.0-hotpotqa-test',
    'nfcorpus': 'beir-v1.0.0-nfcorpus-test',
    'nq': 'beir-v1.0.0-nq-test',
    'bioasq': 'beir-v1.0.0-bioasq-test',



    'mrtydi-ar': 'mrtydi-v1.1-arabic-test',
    'mrtydi-bn': 'mrtydi-v1.1-bengali-test',
    'mrtydi-fi': 'mrtydi-v1.1-finnish-test',
    'mrtydi-id': 'mrtydi-v1.1-indonesian-test',
    'mrtydi-ja': 'mrtydi-v1.1-japanese-test',
    'mrtydi-ko': 'mrtydi-v1.1-korean-test',
    'mrtydi-ru': 'mrtydi-v1.1-russian-test',
    'mrtydi-sw': 'mrtydi-v1.1-swahili-test',
    'mrtydi-te': 'mrtydi-v1.1-telugu-test',
    'mrtydi-th': 'mrtydi-v1.1-thai-test',
}

THE_QRELS = {
    'dl19': 'dl19-passage',
    'dl20': 'dl20-passage',
    "dl21": "dl21-passage",
    "dl22": "dl22-passage",
    'msmarco': 'msmarco-passage-dev-subset',
    'covid': 'beir-v1.0.0-trec-covid-test',
    'arguana': 'beir-v1.0.0-arguana-test',
    'touche': 'beir-v1.0.0-webis-touche2020-test',
    'news': 'beir-v1.0.0-trec-news-test',
    'scifact': 'beir-v1.0.0-scifact-test',
    'fiqa': 'beir-v1.0.0-fiqa-test',
    'scidocs': 'beir-v1.0.0-scidocs-test',
    'nfc': 'beir-v1.0.0-nfcorpus-test',
    'quora': 'beir-v1.0.0-quora-test',
    'dbpedia': 'beir-v1.0.0-dbpedia-entity-test',
    'fever': 'beir-v1.0.0-fever-test',
    'robust04': 'beir-v1.0.0-robust04-test',
    'signal': 'beir-v1.0.0-signal1m-test',
    'fever': 'beir-v1.0.0-fever-test',
    'climate-fever': 'beir-v1.0.0-climate-fever-test',
    'hotpotqa': 'beir-v1.0.0-hotpotqa-test',
    'nfcorpus': 'beir-v1.0.0-nfcorpus-test',
    'nq': 'beir-v1.0.0-nq-test',
    'bioasq': 'beir-v1.0.0-bioasq-test',



    'mrtydi-ar': 'mrtydi-v1.1-arabic-test',
    'mrtydi-bn': 'mrtydi-v1.1-bengali-test',
    'mrtydi-fi': 'mrtydi-v1.1-finnish-test',
    'mrtydi-id': 'mrtydi-v1.1-indonesian-test',
    'mrtydi-ja': 'mrtydi-v1.1-japanese-test',
    'mrtydi-ko': 'mrtydi-v1.1-korean-test',
    'mrtydi-ru': 'mrtydi-v1.1-russian-test',
    'mrtydi-sw': 'mrtydi-v1.1-swahili-test',
    'mrtydi-te': 'mrtydi-v1.1-telugu-test',
    'mrtydi-th': 'mrtydi-v1.1-thai-test',
}

